version: 2.1

jobs:
  test:
    docker:
      - image: circleci/node:14.15.1
        environment:
          PGHOST: 127.0.0.1
          PGUSER: postgres
          NODE_ENV: test
      - image: circleci/postgres:9.6-alpine
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
  
    working_directory: ~/repo

    steps:

      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json"}}
            - v1-dependencies-

      - run:
          name: install npm packages
          command: npm ci

      - save_cache:
          paths:
            - ./node_modules
          key: v1-dependencies-{{ checksum "package.json"}}

      - run:
          name: wait for postgres connection
          command: dockereize -wait tcp://localhost:5432 -timeout 1m

      - run:
          name: run unit tests
          command: npm run coverage

workflows:
  build_test:
    jobs:
      - test

