version: 2.1

jobs:
  test:
    docker:
      - image: circleci/node:14.15.1
      - image: circleci/postgres:11-alpine-ram
        environment:
          POSTGRES_USER:  postgres
          POSTGRES_PASSWORD: postgres  
          POSTGRES_DB: postgres
      - image: redis:latest
  
    working_directory: ~/repo

    steps:

      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json"}}
            - v1-dependencies-

      - run:
          name: install npm packages
          command: npm install

      - save_cache:
          paths:
            - ./node_modules
          key: v1-dependencies-{{ checksum "package.json"}}

      - run:
          name: run unit tests
          command: npm run ci:test

workflows:
  build_test:
    jobs:
      - test

